node {
  stage('Etapa con Git') {  
    sshagent (credentials: ['github-key']) {
      // Con el siguiente comando el ultimo commit id del repositorio que se especifica
      sh 'git ls-remote -h --refs git@github.com:puchevcp/cursojenkins.git main |awk "{print $1}"'
    }
  }
}
